import { motion, AnimatePresence } from 'framer-motion'
import { Sparkles, Search, Zap, Loader2, ShieldCheck, AlertTriangle, AlertCircle, RotateCcw, Copy, Terminal as TerminalIcon } from 'lucide-react'
import { useScanner } from '../hooks/useScanner'

const quickTests = [
  'auth-security-verify.micr0s0ft.net',
  'google.com',
  'paypal-security-check.top/account/unlo',
  'github.com/lovable/lovable'
]

const levelColors = {
  'High Risk': 'text-[var(--danger)]',
  'Suspicious': 'text-[var(--warning)]',
  'Safe': 'text-[var(--success)]',
}

const borderColors = {
  'High Risk': 'border-[var(--danger)]/50',
  'Suspicious': 'border-[var(--warning)]/50',
  'Safe': 'border-[var(--success)]/50',
}

const glowColors = {
  'High Risk': 'shadow-[0_0_20px_rgba(255,51,102,0.3)]',
  'Suspicious': 'shadow-[0_0_20px_rgba(255,189,46,0.3)]',
  'Safe': 'shadow-[0_0_20px_rgba(0,255,148,0.3)]',
}

const statusIcons = {
  danger: AlertTriangle,
  warning: AlertCircle,
  safe: ShieldCheck,
}

export default function Hero() {
  const {
    url,
    setUrl,
    scanning,
    scanStep,
    scanSteps,
    result,
    error,
    recentScans,
    startScan,
    resetScanner
  } = useScanner()

  const copyReport = () => {
    if (!result) return
    const text = `ThreatSpy Scan Report\nURL: ${result.url}\nRisk Score: ${result.riskScore}/100\nRisk Level: ${result.riskLevel}\nTimestamp: ${result.timestamp}\n\nGenerated by ThreatSpy Intelligence Platform`
    navigator.clipboard.writeText(text)
  }

  return (
    <section className="relative overflow-hidden pb-16">
      {/* Background Effects */}
      <div className="absolute inset-0 cyber-grid"></div>
      <div className="noise"></div>
      
      {/* Radar Decoration */}
      <div className="pointer-events-none absolute -right-32 top-10 hidden size-[420px] lg:block">
        <div className="absolute inset-0 rounded-full border border-[var(--cyber)]/20"></div>
        <div className="absolute inset-8 rounded-full border border-[var(--cyber)]/15"></div>
        <div className="absolute inset-16 rounded-full border border-[var(--cyber)]/10"></div>
        <div className="absolute inset-24 rounded-full border border-[var(--cyber)]/8"></div>
        <div className="radar-sweep absolute inset-0">
          <div className="absolute left-1/2 top-0 h-1/2 w-px bg-gradient-to-b from-[var(--cyber)] to-transparent"></div>
          <div className="absolute left-1/2 top-0 h-1/2 w-32 origin-bottom-left -translate-x-px bg-gradient-to-b from-[var(--cyber)]/30 to-transparent blur-sm"></div>
        </div>
        <div className="absolute left-1/2 top-1/2 size-2 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[var(--cyber)] glow-cyber"></div>
      </div>

      <div className="mx-auto max-w-7xl px-4 pb-12 pt-16 sm:px-6 lg:pt-24 relative z-10">
        
        {/* Main Header Content */}
        <motion.div 
          initial={{ opacity: 0, y: 14 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, ease: "easeOut" }}
          className="max-w-3xl"
        >
          {/* Badge */}
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[var(--cyber)]/30 bg-[var(--cyber)]/5 px-3 py-1.5">
            <Sparkles className="size-3 text-[var(--cyber)]" />
            <span className="font-mono text-[10px] uppercase tracking-[0.2em] text-[var(--cyber)]">
              AI-Powered · 14 Detection Vectors · Real-time
            </span>
          </div>

          <h1 className="mb-5 text-balance text-5xl font-bold leading-[1.05] tracking-tight sm:text-6xl lg:text-7xl">
            <span className="text-gradient-cyber">Next-Gen</span> Phishing<br />
            Intelligence Platform
          </h1>
          
          <p className="mb-2 max-w-[60ch] text-pretty text-lg text-muted-foreground">
            Enterprise-grade URL forensics combining heuristic analysis, machine learning, and live global threat feeds — built for SOC operators and security teams.
          </p>
          
          <p className="mb-10 font-mono text-sm text-[var(--cyber)] cursor-blink"></p>
        </motion.div>

        {/* Scanner Form Section */}
        <motion.div 
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2, ease: "easeOut" }}
          className="relative max-w-3xl"
        >
          <div className="relative overflow-hidden rounded-2xl glass-strong p-1.5 glow-cyber transition-all">
            <form 
              className="relative flex flex-col items-stretch gap-2 rounded-xl bg-background/60 p-2 sm:flex-row" 
              onSubmit={(e) => { e.preventDefault(); startScan() }}
            >
              <div className="relative flex-1">
                <Search className="pointer-events-none absolute left-4 top-1/2 size-4 -translate-y-1/2 text-[var(--cyber)]" />
                <input 
                  type="text" 
                  spellCheck="false" 
                  value={url}
                  onChange={(e) => setUrl(e.target.value)}
                  disabled={scanning}
                  placeholder="https://suspicious-domain.example/login" 
                  className="h-14 w-full rounded-lg bg-transparent pl-11 pr-4 font-mono text-sm text-foreground outline-none placeholder:text-muted-foreground/60 focus:ring-1 focus:ring-[var(--cyber)]/50 transition-all disabled:opacity-50" 
                />
              </div>
              <button 
                type="submit" 
                disabled={scanning}
                className="group relative inline-flex h-14 items-center justify-center gap-2 overflow-hidden rounded-lg bg-gradient-to-r from-[var(--cyber)] to-[var(--cyber-glow)] px-8 text-sm font-semibold text-primary-foreground shadow-[0_8px_30px_-8px_var(--cyber)] transition-transform hover:scale-[1.02] disabled:opacity-70 disabled:hover:scale-100"
              >
                {scanning ? (
                  <>
                    <Loader2 className="size-4 animate-spin" />
                    <span>Scanning...</span>
                  </>
                ) : (
                  <>
                    <Zap className="size-4" strokeWidth={2.5} />
                    <span>Run Deep Scan</span>
                  </>
                )}
              </button>
            </form>

            {/* Scan Progress Sequence */}
            <AnimatePresence>
              {scanning && (
                <motion.div 
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  className="px-4 sm:px-5 pb-4 overflow-hidden"
                >
                  <div className="h-px bg-gradient-to-r from-transparent via-[var(--cyber)]/50 to-transparent my-3 shadow-[0_0_10px_rgba(10,239,255,0.3)]" />
                  <div className="space-y-1.5">
                    {scanSteps.slice(0, scanStep + 1).map((step, i) => (
                      <motion.div
                        key={i}
                        initial={{ opacity: 0, x: -10 }}
                        animate={{ opacity: 1, x: 0 }}
                        className="flex items-center gap-2"
                      >
                        {scanStep === i && scanStep < scanSteps.length - 1 ? (
                          <Loader2 className="size-3 text-[var(--cyber)] animate-spin shrink-0" />
                        ) : (
                          <div className="size-1.5 rounded-full bg-[var(--success)] shrink-0 shadow-[0_0_8px_rgba(0,255,148,0.5)]" />
                        )}
                        <span className={`text-xs font-mono ${scanStep === i && scanStep < scanSteps.length - 1 ? 'text-[var(--cyber)]' : 'text-muted-foreground'}`}>
                          {step}
                        </span>
                      </motion.div>
                    ))}
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* Validation Error */}
          <AnimatePresence>
            {error && (
              <motion.p
                initial={{ opacity: 0, y: -5 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                className="text-[var(--danger)] text-xs font-mono mt-3 px-2"
              >
                {error}
              </motion.p>
            )}
          </AnimatePresence>

          {/* Quick Links */}
          {!result && (
            <div className="mt-5 flex flex-wrap items-center gap-2">
              <span className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">Quick test:</span>
              {quickTests.map((testStr, i) => (
                <button 
                  key={i}
                  type="button" 
                  onClick={() => startScan(testStr)}
                  disabled={scanning}
                  className="truncate rounded-md border border-border/60 bg-surface/50 px-2.5 py-1 font-mono text-[11px] text-muted-foreground transition-all hover:border-[var(--cyber)]/40 hover:bg-[var(--cyber)]/5 hover:text-[var(--cyber)] disabled:opacity-50"
                >
                  {testStr}
                </button>
              ))}
            </div>
          )}
        </motion.div>

        {/* Results Section */}
        <AnimatePresence mode="wait">
          {result && (
            <motion.div
              key={result.url}
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -30 }}
              className="max-w-4xl mt-12"
            >
              {/* Main Score Card */}
              <div className={`glass-strong rounded-2xl p-6 sm:p-8 border-l-4 ${borderColors[result.riskLevel]} ${glowColors[result.riskLevel]} transition-all duration-500`}>
                <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 sm:gap-6">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-3 mb-1">
                      <h3 className="text-xl sm:text-2xl font-bold text-foreground">Forensic Scan Complete</h3>
                      <span className="text-xs text-muted-foreground font-mono bg-surface px-2 py-0.5 rounded-md border border-border/50">{result.timestamp}</span>
                    </div>
                    <p className="text-sm text-muted-foreground font-mono truncate max-w-[90%]">{result.url}</p>
                  </div>

                  <div className="flex items-center gap-6 sm:gap-8 bg-surface/40 p-4 rounded-xl border border-border/40">
                    <div className="text-center">
                      <div className={`text-4xl sm:text-5xl font-black tracking-tight ${levelColors[result.riskLevel]}`}>
                        {result.riskScore}
                      </div>
                      <div className="text-[10px] text-muted-foreground uppercase tracking-wider mt-1 font-mono">Risk Score</div>
                    </div>
                    <div className="w-px h-12 bg-border/60" />
                    <div className="text-center">
                      <div className={`text-xl sm:text-2xl font-bold ${levelColors[result.riskLevel]}`}>
                        {result.riskLevel}
                      </div>
                      <div className="text-[10px] text-muted-foreground uppercase tracking-wider mt-1 font-mono">Verdict</div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Security Checks Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-6">
                {result.checks.map((check, idx) => {
                  const Icon = statusIcons[check.status] || ShieldCheck
                  const colorClasses = {
                    danger: 'border-[var(--danger)]/30 bg-[var(--danger)]/5 hover:border-[var(--danger)]/50',
                    warning: 'border-[var(--warning)]/30 bg-[var(--warning)]/5 hover:border-[var(--warning)]/50',
                    safe: 'border-[var(--success)]/30 bg-[var(--success)]/5 hover:border-[var(--success)]/50',
                  }
                  const iconColors = {
                    danger: 'text-[var(--danger)]',
                    warning: 'text-[var(--warning)]',
                    safe: 'text-[var(--success)]',
                  }

                  return (
                    <motion.div
                      key={check.id}
                      initial={{ opacity: 0, y: 15 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: 0.1 * idx, ease: "easeOut" }}
                      className={`rounded-xl border p-5 ${colorClasses[check.status]} transition-all duration-300`}
                    >
                      <div className="flex items-start justify-between mb-3">
                        <Icon className={`size-5 ${iconColors[check.status]}`} />
                        <span className={`text-[10px] font-mono font-bold uppercase px-2 py-0.5 rounded border ${iconColors[check.status]} border-current/30 bg-background/50`}>
                          {check.status === 'safe' ? 'PASS' : 'FLAGGED'}
                        </span>
                      </div>
                      <h4 className="font-semibold text-sm text-foreground mb-1.5">{check.name}</h4>
                      <p className="text-xs text-muted-foreground leading-relaxed">{check.message}</p>
                    </motion.div>
                  )
                })}
              </div>

              {/* Action Buttons */}
              <div className="flex flex-wrap items-center gap-3 mt-8">
                <button 
                  onClick={resetScanner} 
                  className="group relative inline-flex items-center gap-2 px-5 py-2.5 text-xs font-semibold rounded-lg bg-surface border border-border/60 hover:bg-[var(--cyber)]/10 hover:border-[var(--cyber)]/40 hover:text-[var(--cyber)] transition-all"
                >
                  <RotateCcw className="size-3.5" />
                  New Scan
                </button>
                <button 
                  onClick={copyReport} 
                  className="group relative inline-flex items-center gap-2 px-5 py-2.5 text-xs font-semibold rounded-lg bg-surface border border-border/60 hover:bg-foreground transition-all"
                >
                  <Copy className="size-3.5" />
                  Copy Report
                </button>
                <a 
                  href="#terminal" 
                  className="group relative inline-flex items-center gap-2 px-5 py-2.5 text-xs font-semibold rounded-lg bg-surface border border-border/60 hover:bg-foreground transition-all"
                >
                  <TerminalIcon className="size-3.5" />
                  View Raw Logs
                </a>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Recent Scans History (Only show if not scanning and no active result) */}
        <AnimatePresence>
          {recentScans.length > 0 && !result && !scanning && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="max-w-3xl mt-12"
            >
              <div className="text-xs text-muted-foreground font-mono mb-3 flex items-center gap-2">
                <div className="size-1.5 rounded-full bg-[var(--success)] shadow-[0_0_8px_rgba(0,255,148,0.5)] animate-pulse" />
                Recent Intelligence
              </div>
              <div className="glass rounded-xl divide-y divide-border/30 overflow-hidden">
                {recentScans.map((scan, i) => (
                  <div key={i} className="flex items-center justify-between px-4 py-3 text-xs font-mono hover:bg-surface/50 transition-colors cursor-pointer" onClick={() => startScan(scan.url)}>
                    <span className="text-muted-foreground/60 w-20 shrink-0">{scan.time}</span>
                    <span className="flex-1 truncate px-3 text-foreground/80">{scan.domain}</span>
                    <span className={`font-semibold ${levelColors[scan.level]} shrink-0 flex items-center gap-2 bg-background/50 px-2 py-1 rounded border border-border/40`}>
                      {scan.level} <span className="opacity-50">·</span> {scan.score}
                    </span>
                  </div>
                ))}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </section>
  )
}
